# Generated by Django 6.0.1 on 2026-06-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcredential',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
