# Generated by Django 6.0.1 on 2026-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
